<?php

/**
 * PluginMailQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMailQueuePlugin
 * @subpackage model
 * @author     Hiromi Hishida <info@77-web.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginMailQueue extends BaseMailQueue
{

}